<?php

/*
 * Copyright 2017 Aaron Scherer
 *
 * This source file is subject to the license that is bundled
 * with this source code in the file LICENSE
 *
 * @package     restcord/restcord
 * @copyright   Aaron Scherer 2017
 * @license     MIT
 */

namespace RestCord\Model\Channel;

/**
 * Message Model
 */
class Message {

	/**
	 * sent with Rich Presence-related chat embeds
	 *
	 * @var array|null
	 */
	public $activity;

	/**
	 * sent with Rich Presence-related chat embeds
	 *
	 * @var array|null
	 */
	public $application;

	/**
	 * if the message is a response to an Interaction, this is the id of the interaction's application
	 *
	 * @var int|null
	 */
	public $application_id;

	/**
	 * Deprecated previously the sticker asset hash, now an empty string
	 *
	 * @var string
	 */
	public $asset;

	/**
	 * any attached files
	 *
	 * @var array
	 */
	public $attachments;

	/**
	 * the author of this message (not guaranteed to be a valid user, see below)
	 *
	 * @var array
	 */
	public $author;

	/**
	 * whether or not the sticker is available
	 *
	 * @var bool|null
	 */
	public $available = false;

	/**
	 * id of the channel the message was sent in
	 *
	 * @var int
	 */
	public $channel_id;

	/**
	 * sent if the message contains components like buttons, action rows, or other interactive components
	 *
	 * @var array Array of message components|null
	 */
	public $components;

	/**
	 * contents of the message
	 *
	 * @var string
	 */
	public $content;

	/**
	 * description of the sticker
	 *
	 * @var string
	 */
	public $description;

	/**
	 * when this message was edited (or null if never)
	 *
	 * @var \DateTimeImmutable
	 */
	public $edited_timestamp;

	/**
	 * any embedded content
	 *
	 * @var array
	 */
	public $embeds;

	/**
	 * message flags combined as a bitfield
	 *
	 * @var int|null
	 */
	public $flags;

	/**
	 * type of sticker format
	 *
	 * @var int
	 */
	public $format_type;

	/**
	 * id of the guild that owns this sticker
	 *
	 * @var int|null
	 */
	public $guild_id;

	/**
	 * id of the sticker
	 *
	 * @var int
	 */
	public $id;

	/**
	 * sent if the message is a response to an Interaction
	 *
	 * @var array|null
	 */
	public $interaction;

	/**
	 * member properties for this message's author
	 *
	 * @var array|null
	 */
	public $member;

	/**
	 * channels specifically mentioned in this message
	 *
	 * @var array|null
	 */
	public $mention_channels;

	/**
	 * whether this message mentions everyone
	 *
	 * @var bool
	 */
	public $mention_everyone = false;

	/**
	 * roles specifically mentioned in this message
	 *
	 * @var array
	 */
	public $mention_roles;

	/**
	 * users specifically mentioned in the message
	 *
	 * @var array
	 */
	public $mentions;

	/**
	 * data showing the source of a crosspost, channel follow add, pin, or reply message
	 *
	 * @var array|null
	 */
	public $message_reference;

	/**
	 * name of the sticker
	 *
	 * @var string
	 */
	public $name;

	/**
	 * used for validating a message was sent
	 *
	 * @var integer or string|null
	 */
	public $nonce;

	/**
	 * id of the pack the sticker is from
	 *
	 * @var int|null
	 */
	public $pack_id;

	/**
	 * party_id from a Rich Presence event
	 *
	 * @var string|null
	 */
	public $party_id;

	/**
	 * whether this message is pinned
	 *
	 * @var bool
	 */
	public $pinned = false;

	/**
	 * reactions to the message
	 *
	 * @var array|null
	 */
	public $reactions;

	/**
	 * the message associated with the message_reference
	 *
	 * @var array|null
	 */
	public $referenced_message;

	/**
	 * a sticker's sort order within a pack
	 *
	 * @var int|null
	 */
	public $sort_value;

	/**
	 * Deprecated the stickers sent with the message (bots currently can only receive messages with stickers, not send)
	 *
	 * @var array|null
	 */
	public $stickers;

	/**
	 * a unicode emoji representing the sticker's expression
	 *
	 * @var string
	 */
	public $tags;

	/**
	 * the thread that was started from this message, includes thread member object
	 *
	 * @var array|null
	 */
	public $thread;

	/**
	 * when this message was sent
	 *
	 * @var \DateTimeImmutable
	 */
	public $timestamp;

	/**
	 * whether this was a TTS message
	 *
	 * @var bool
	 */
	public $tts = false;

	/**
	 * type of message activity
	 *
	 * @var int
	 */
	public $type;

	/**
	 * the user that uploaded the sticker
	 *
	 * @var array|null
	 */
	public $user;

	/**
	 * if the message is generated by a webhook, this is the webhook's id
	 *
	 * @var int|null
	 */
	public $webhook_id;

	/**
	 * @param array $content
	 */
	public function __construct(array $content = null) {
		if (null === $content) {
		    return;
		}
		                    
		foreach ($content as $key => $value) {
		    $key = lcfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $key))));
		    if (property_exists($this, $key)) {
		        $this->{$key} = $value;
		    }
		}
	}
}